name: semantic-release
on:
  push:
    branches:
      - main
      - package-release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      # id-token: write
      # packages: write
      # pull-requests: write
      # repository-projects: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v3.0.0
        with:
          persist-credentials: false

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GH_UTL: 'https://github.com/PheasantDevil'
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}